### ISSUE TITLE
[Improvement] Make the menu items customizable

### ISSUE THREAD

**Issue by orkun1675** [thomasvaeth/trophy-ghost#11]
The menu bars currently read:
- Posts
- Tags
and are not customizable unless through editing the hbs file. Is there a way to make these customizable? I would rather use "Categories" instead of "Tags".

In case you are busy, I will also work on these issues I opened when I have the time and open pull request.

**Comment by thomasvaeth** [comment]
The menu bar cannot be edited through Ghost since it's not really a menu. The links don't go to a new page, but rather a new tab. And they're called Tags on Ghost (tags.hbs), so that's why they're called Tags here.
