### ISSUE TITLE
Site refuses to load

### ISSUE THREAD

**Issue by stormgrass** [thomasvaeth/trophy-ghost#4]
Hello! I'm using Ghost v.0.11.7 via Cloudron and tried setting it up with your theme. I downloaded the master branch, then uploaded the extracted folder to the /theme folder.

After activating the theme the site refuses to load and the console gives me these error messages:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src 'unsafe-inline' https://www.mydomain.com”). Source: call to eval() or related function blocked by CSP.  (unknown)
GET 
https://www.mydomain.com/3rdparty/css/font-awesome.min.css [HTTP/1.1 502 Bad Gateway 30ms]
GET 
https://www.mydomain.com/3rdparty/bootstrap-3.3.7.min.css [HTTP/1.1 502 Bad Gateway 40ms]
```
Ultimately the backend refuses to load as well, forcing me to delete the whole theme folder, then restarting Ghost to activate a fallback theme.

Not entirely sure whether it's a Cloudron problem or related to your theme, but maybe you've got any pointers?

Public API is activated.

Thanks in advance!

**Comment by thomasvaeth** [comment]
This shouldn't have anything to do with my theme. I don't use Bootstrap and CDNJS is used for Font Awesome.
