### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by okeehou** [thomasvaeth/trophy-ghost#5]
Hello, thanks sharing your great theme. I have some questions:

1. How to edit the biography that will appear on posts they write?
2. How to change from tag to categories?

Many thanks!

<img width="531" alt="1" src="https://cloud.githubusercontent.com/assets/19646526/26755130/dd1fd722-48b9-11e7-9d56-1105c109de06.png">
<img width="256" alt="2" src="https://cloud.githubusercontent.com/assets/19646526/26755131/dd22d94a-48b9-11e7-95b4-6434d75e033e.png">

**Comment by orkun1675** [comment]
2.

You can change line 18 in "index.hbs" from:
```<li class="tabs__item">Tags</li>```  
to:
```<li class="tabs__item">Categories</li>```

**Comment by zzedgat2012** [comment]
Hey, same question here, how to edit Authors Image and Bio.

**Comment by thomasvaeth** [comment]
You should be able to go to Team in the left hand navigation, click on whatever team member you want to edit, and change the image/enter a bio.
