### ISSUE TITLE
the commit "Updated dev dependencies" breaks the JS

### ISSUE THREAD

**Issue by orkun1675** [thomasvaeth/trophy-ghost#9]
The last commit breaks the entire JS for the site. Navigation isn't functioning anymore. I fixed the console error about WeakMap but that didn't help either.

**Comment by thomasvaeth** [comment]
I just [pushed](https://github.com/thomasvaeth/trophy-ghost/commit/20d2b9f82815abc5b8033fd8316568956f7ce191) an updated version of WOW.js.

**Comment by orkun1675** [comment]
Thank you for the fast update!
